e:==write sys$output
e "(B)0"
e ""
e "[1;5m"
e "                                                                   "
e "       //       //////   //////        //////   //////   //////    "
e "      aa/      aaaaaa/  aaaaaa//      aaaaaa/  aaaaaa/  aaaaaa//   "
e "      aa/      aa/      aa/   a//         a/   aa/      aa/   a/   "
e "      aa/      aa/////  aa/    a/        a/    aa/////  aa////a/   "
e "     saa/ssssssaaaaaa/ssaa/ssssa/sssssssa/sssssaaaaaa/ssaaaaaa/sss "
e "    / aa/      aa/      aa/   /a/      a/      aa/      aa/      / " 
e "   /  aa/////  aa/////  aa////a/      a//////  aa/////  aa/     /  "
e "  /   aaaaaa/  aaaaaa/  aaaaaa/       aaaaaa/  aaaaaa/  aa/    /   "
e " /                                                            /    "
e " ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo     "
e " "
e "                                            -THE KEEPER            "
e "(B)B"
e "[0m"
 
